### PR TITLE
Added some Text animations

### LINKED ISSUE #6: Add text animations

### PR DESCRIPTION
**Pull request by Gulshan-11**
Hey @Rodent12 I have added some text animations in this pr.
closes #6

### CODE REVIEW

**Comment by Rodent12** [comment]
@Gulshan-11 could you please mention the animation type in the folder name?

**Comment by Gulshan-11** [comment]
@Rodent12 I have mentioned it as a folder name 
#6

**Comment by Gulshan-11** [comment]
hey @Rodent12 can you look into this and merge the pr

**Comment by Rodent12** [comment]
Okay

> hey @Rodent12 can you look into this and merge the pr

Sure!

**Pull request merged**
